# Tensors

Everything in PyTorch works on the basic unit of a `Tensor`. We will be working with these basic units in this notebook. Tensors are multidimensional units.

In [19]:
# Imports
import torch
import numpy as np

print("Imported successfully")

Imported successfully


In [4]:
x = torch.empty(1)  # A one dimensional tensor is like a scalar value
# This tensor is empty with no value given to it for now
print(x)
# This is a 1D tensor with one element
# We can also for example have a 1D tensor with 3 elements
a = torch.empty(3)
print(a)

tensor([0.])
tensor([0.0000e+00, 6.6161e-06, 5.6052e-45])


In [3]:
# We can have tensors in 2D and 3D
y = torch.empty(3, 5)  # 3 rows and 5 columns
z = torch.empty(4, 4, 4) # 4x4x4 tensor, but it's still 3 dimensional
print(y)
print(z)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.8009e+24],
        [4.5916e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[[-5.0940e-02,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-8.8030e-02,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00]],

        [[-6.4657e-02,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-1.5421e-01,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00]],

        [[-1.0681e-01,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-3.7344e+00,  7.1606e-43,  0.0000e+00,  7.1606e-43],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00]],

        [[-1.1874e-01,  7.1

In [7]:
# We can create a tensor with random values like so:
b = torch.rand(2, 2)
b

tensor([[0.8401, 0.5294],
        [0.2684, 0.2848]])

In [8]:
# Similar to numpy, we can have a tensor of zeroes
c = torch.zeros(2, 2)
# But also a tensor of ones
d = torch.ones(2, 2)
print(c)
print(d)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


By default tensors have the datatype of `torch.float32`. We can check this if we print out the `dtype` attribute of the tensor. We can change this type by explicitly calling an argument to change it when creating a tensor. <br>

Some of the types are:
- int
- double
- float64
- float32 (default)
- float16

In [10]:
print(d.dtype)
e = torch.ones(2, 2, dtype=torch.int)
e

torch.float32


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [11]:
# We can check the size of a tensor like so:
e.size()

torch.Size([2, 2])

In [12]:
# We can construct a tensor using data like a python list
f = torch.tensor([2.5, 0.1])
f

tensor([2.5000, 0.1000])

## Tensor operations

In [15]:
g = torch.rand(2, 2)
f = torch.rand(2, 2)
print(g)
print(f)

# Simple addition: (element wise)
print(g + f) 
# Another way to do this is:
print(torch.add(g, f))
# If we want to do in place addition:
f.add_(g)
print(f)

tensor([[0.7003, 0.5694],
        [0.3961, 0.6893]])
tensor([[0.5705, 0.4116],
        [0.1332, 0.7234]])
tensor([[1.2708, 0.9810],
        [0.5293, 1.4128]])
tensor([[1.2708, 0.9810],
        [0.5293, 1.4128]])
tensor([[1.2708, 0.9810],
        [0.5293, 1.4128]])


### Important to note: 
In PyTorch, every method with a trailing _ (underscore), will perform an in-place operation. I.E. it will modify the first value by performing the operation on it instead of storing the result in a var for example

Similarly:

```py
a = b - c
a = torch.sub(b, c)
a = b * c
a = torch.mul(b, c)
a = b / c
a = torch.div(b, c)
```

And if we were going in place:

```py
b.sub_(c)
b.mul_(c)
b.div_(c)
```

In [16]:
# Now for some slicing operations
# These should be similar to numpy arrays
tensor1 = torch.rand(5, 3)
print(tensor1)
print(tensor1[:, 0])  # All rows but only column 0
print(tensor1[1, :])  # Row 1 but all columns

# We can also get only one element like so
print(tensor1[1, 1])
# NOTE: if we have a tensor with ONLY one element, we can call item()
print(tensor1[1, 1].item())  # This will return the actual value
# THIS ONLY WORKS FOR 1 X 1 (scalar) tensors

tensor([[0.3232, 0.9370, 0.5775],
        [0.0815, 0.0532, 0.7919],
        [0.5434, 0.5884, 0.1220],
        [0.6453, 0.7970, 0.4350],
        [0.5840, 0.8801, 0.4985]])
tensor([0.3232, 0.0815, 0.5434, 0.6453, 0.5840])
tensor([0.0815, 0.0532, 0.7919])
tensor(0.0532)
0.053211748600006104


## Reshaping Tensors

In [18]:
tensor2 = torch.rand(4, 4)
print(tensor2)

# Reshape with view method
reshaped = tensor2.view(16)
print(reshaped)
# The number of elements must remain the same, 4x4 2D = 16 1D

reshaped2 = tensor2.view(-1, 8)
print(reshaped2)
# By giving -1 pytorch will autodetect the right size by calculating for that dimension
# In this case it must be a 2x8

tensor([[0.3887, 0.7408, 0.8059, 0.1847],
        [0.1911, 0.0798, 0.1407, 0.9136],
        [0.9969, 0.9292, 0.7366, 0.1348],
        [0.1282, 0.6088, 0.3945, 0.0687]])
tensor([0.3887, 0.7408, 0.8059, 0.1847, 0.1911, 0.0798, 0.1407, 0.9136, 0.9969,
        0.9292, 0.7366, 0.1348, 0.1282, 0.6088, 0.3945, 0.0687])
tensor([[0.3887, 0.7408, 0.8059, 0.1847, 0.1911, 0.0798, 0.1407, 0.9136],
        [0.9969, 0.9292, 0.7366, 0.1348, 0.1282, 0.6088, 0.3945, 0.0687]])


## Converting between Numpy and Torch tensors

In [21]:
# torch tensor
torchtens = torch.ones(5)
print(torchtens)
# convert to numpy:
nptens = torchtens.numpy()
print(nptens)

# Convert back:
torchtens2 = torch.from_numpy(nptens)  # Optional dtype arg
print(torchtens2)  # default floa64

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


### Important
NOTE that if the tensor is on the GPU, converting a tensor will work but both the tensors, numpy and torch, will have the same memory location, so any in place operations will change the values of both. Additionally, numpy tensors can only handle CPU whereas torch ones can handle GPU as well, which can cause complications during interconversion.

In [22]:
# By default the requires_grad argument is False
optimized_tensor = torch.ones(5, requires_grad=True)  # can be set true
print(optimized_tensor)

# This is needed for tensors that are to be optimized
# Pytorch needs to know so it can calc the gradient

tensor([1., 1., 1., 1., 1.], requires_grad=True)
